### ISSUE TITLE
Feature: safety report in readme

### ISSUE THREAD

**Issue by mleonhard** [rust-secure-code/cargo-geiger#151]
I want a tool to automatically update update a safety report section in my project's readme file.  Requirements:

- Run `cargo-geiger` on the current project
- Convert the report into Markdown format
- Look for a `# Safety Report` section in `Readme.md` and replace it with the generated report

Advanced features:
- An argument with the name of the markdown file to update
- An argument with the name of the section to replace
- Check the git repository, see if there's a tag at HEAD in the current branch, and include the tag in the report.  This could be a separate program.
- An option to include the branch name in the report.
- An option to include the git commit ID in the report.
- For each unsafe crate, link to a ticket about making the crate safer.  So folks can easily express their desire for more safety in code and dependencies.  For crates without such tickets, link to a page explaining how to file the ticket and add the link to cargo-geiger (make a PR).  When crate maintainers [delete tickets that ask for more safety](https://medium.com/@shnatsel/smoke-testing-rust-http-clients-b8f2ee5db4e6#7543), include a link to a ticket in a different repository.  The [isaacs/github](https://github.com/isaacs/github) repository is an example of this technique.

Similar tools: [clog-cli](https://crates.io/crates/clog-cli)

**Comment by jmcconnell26** [comment]
I had an initial stab at the base feature request here https://github.com/rust-secure-code/cargo-geiger/pull/156
This seems like a really useful feature to have, and I like the sound of the advanced features as well, I can keep plugging away at them, if no one has any objections?

**Comment by 8573** [comment]
@mleonhard wrote—
> * For each unsafe crate, link to a ticket about making the crate safer.  So folks can easily express their desire for more safety in code and dependencies.  For crates without such tickets, link to a page explaining how to file the ticket and add the link to cargo-geiger (make a PR).

Rather than keeping this information inside cargo-geiger, it might be better kept in, say, a hypothetical file <https://github.com/rust-secure-code/safety-dance/blob/master/crate-info.yaml> containing something like—
<details>
<summary>Example</summary>

```yaml
- arrayref:
    repo: "https://github.com/droundy/arrayref"
    ticket: 50
    upstream-tickets:
      - "https://github.com/droundy/arrayref/issues/18"

- clap:
    repo: "https://github.com/clap-rs/clap"
    ticket: 49

- prost:
    repo: "https://github.com/danburkert/prost"
    ticket: 68

- ureq:
    repo: "https://github.com/algesten/ureq"
    ticket: 59
    status:
      unsafe-forbidden:
        date: 2020-06-16
        see: ["https://github.com/algesten/ureq/pull/68"]

- miniz_oxide:
    repo: "https://github.com/Frommi/miniz_oxide"
    ticket: 2
    status:
      unsafe-forbidden:
        date: 2019-08-09
        see: ["https://github.com/Frommi/miniz_oxide/pull/56"]

- flate2:
    repo: "https://github.com/rust-lang/flate2-rs"
    ticket: 32
    status:
      waiting:
        - for: author-response
          since: 2019-11-01
          see: ["https://github.com/rust-lang/flate2-rs/issues/220"]
        - for: library-support
          since: 2019-11-01
          see: ["https://github.com/rust-secure-code/safety-dance/issues/32#issuecomment-548833236"]
...
```
</details>

The ticket numbers refer to [Safety Dance tickets](https://github.com/rust-secure-code/safety-dance/issues), not the crates' tickets.

@mleonhard wrote—
> When crate maintainers [delete tickets that ask for more safety](https://medium.com/@shnatsel/smoke-testing-rust-http-clients-b8f2ee5db4e6#7543), include a link to a ticket in a different repository.  The [isaacs/github](https://github.com/isaacs/github) repository is an example of this technique.

If, say, a crate is forked by people who want to make it safer,¹ someone could post this information as a comment on the crate's Safety Dance ticket. Compared to filing a pull request for a patch to a list maintained by the Secure Code Working Group of crates and their tickets, a casual comment on a ticket would both have less administrative overhead and, I suspect, especially if made by a non-member of the Working Group, have less risk of controversy for the Working Group than would linking from a Group-maintained resource to a resource that could be seen as inherently antagonistic towards the original developer.

(¹ If you do this, consider not using the "Fork" button on GitHub — if the fork is known to GitHub as a fork, the original developer can delete it by blocking you.)
