### ISSUE TITLE
manifest: `git` deps without `rev` cause panic

### ISSUE THREAD

**Issue by ginger51011** [rust-secure-code/cargo-geiger#461]
I'm currently running `cargo-geiger` on a project, and I get a problem when running geiger with the output set to JSON. With exactly the same settings, without the `--output-format Json`, I get a full tree output.

I get the following backtrace

```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /home/emil/.cargo/registry/src/github.com-XXX/cargo-geiger-0.11.5/src/mapping/geiger.rs:49:18
stack backtrace:
   0: rust_begin_unwind
             at /rustc/7aa413d59206fd511137728df3d9e0fd377429bd/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/7aa413d59206fd511137728df3d9e0fd377429bd/library/core/src/panicking.rs:64:14
   2: core::panicking::panic
             at /rustc/7aa413d59206fd511137728df3d9e0fd377429bd/library/core/src/panicking.rs:114:5
   3: cargo_geiger::mapping::geiger::handle_source_repr
   4: cargo_geiger::mapping::geiger::<impl cargo_geiger::mapping::ToCargoGeigerSource for cargo_metadata::PackageId>::to_cargo_geiger_source
   5: cargo_geiger::mapping::metadata::<impl cargo_geiger::mapping::ToCargoGeigerPackageId for cargo_metadata::PackageId>::to_cargo_geiger_package_id
   6: cargo_geiger::scan::package_metrics
   7: cargo_geiger::scan::default::scan_unsafe
   8: cargo_geiger::scan::scan
   9: cargo_geiger::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

I'm running nightly Rust (required for the package I'm checking), these are some versions:

```console
cargo -V
cargo 1.70.0-nightly (15d090969 2023-03-21)
rustc -V
rustc 1.70.0-nightly (db0cbc48d 2023-03-26)
cargo geiger -V
cargo-geiger 0.11.5
```

Please tell me if more information would be helpful, and thanks for developing the `cargo-geiger`!

**Comment by pinkforest** [comment]
Thanks - I would like to replicate - what dependencies and on which project / package/s or workspace (if public) ?

**Comment by pinkforest** [comment]
Also can we try with stable ? rustup default stable

**Comment by ginger51011** [comment]
Unfortunately, the project is not public. However there is the `Cargo.toml` dependencies

```toml
[dependencies]
clap = { version = "4.1.4", features = ["wrap_help", "derive"] }
indicate = { path = "../libredacted", version = "^0.1.0" }
serde = { version = "^1.0", features = ["derive"] }
serde_json = "1.0.93"

[dev-dependencies]
trycmd = "0.14.12"
```

and for `libredacted`

```toml
[dependencies]
trustfall = { git = "https://github.com/ginger51011/trustfall" }
serde = { version = "=1.0.156", features = ["derive"] }
ron = "0.8.0"
serde_json = "1.0.93"
cargo_metadata = "0.15.3"
octorust = { version = "0.3", features = ["httpcache", "rustls-tls"] }
reqwest = "0.11.14"
once_cell = "1.17.1"
tokio = "1.25.0"
git-url-parse = "0.4.4"
rustsec = "0.26.4"
cvss = "2.0.0"
thiserror = "1.0.38"
chrono = "0.4.23"
cargo_toml = "0.15.2"
walkdir = "2"
cargo = "0.69.0"
dirs = "5.0.0"

[dev-dependencies]
test-case = "3.0.0"
global_counter = { version = "0.2.2", default-features = false }
```
